language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements/dev-requirements.txt

script:
    - python -m unittest discover
    - coverage erase
    - coverage run --source app -m unittest  discover && coverage html

after_success:
  - bash <(curl -s https://codecov.io/bash)

