# docker-compose.yml
version: '3'
services:
  flask:
    image: webapp-flask:latest # name for the image
    build: #build information (local image)
      context: . #use only this directory as context
      dockerfile: Dockerfile #dockerfile to create the image
    ports:
      - 8000:5000 #map the port
    environment:
      DATABASE_URL: 'postgresql://root:root@database:5432'
    depends_on:
      - database

  database:
      container_name: flask_postgres
      restart: always
      image: postgres:12.0-alpine
      environment:
        POSTGRES_USER: 'root'
        POSTGRES_PASSWORD: 'root'
      env_file:
        - .env
      volumes:
        - my-datavolume:/var/lib/postgresql
      ports:
        - 5432:5432
volumes:
  my-datavolume:
